# Generated by Django 6.1.1 on 2026-09-22 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_hierarchique',
            field=models.CharField(choices=[('AGENT', 'Agent'), ('CHEF_SERVICE', 'Chef de service'), ('DIRECTEUR', 'Directeur'), ('CHEF_CABINET', 'Chef de cabinet')], default='AGENT', max_length=20),
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('directeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direction_dirigee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('chef_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_dirige', to=settings.AUTH_USER_MODEL)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='accounts.direction')),
            ],
            options={
                'unique_together': {('nom', 'direction')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='service',
            field=models.ForeignKey(blank=True, help_text="Service de rattachement de l'agent (vide pour un directeur ou le chef de cabinet).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='accounts.service'),
        ),
    ]
