# Generated by Django 6.1.1 on 2026-09-22 18:21

import conges.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('libelle', models.CharField(max_length=100)),
                ('duree_min_jours', models.PositiveIntegerField(help_text='Durée minimale en jours calendaires (ex. 90 pour la maternité).')),
                ('duree_max_jours', models.PositiveIntegerField(blank=True, help_text='Durée maximale, si plafonnée. Vide si la durée dépend uniquement de la décision du directeur.', null=True)),
                ('jours_ouvrables_uniquement', models.BooleanField(default=False, help_text='Coché pour le congé normal (30 jours ouvrables).')),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeJustificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('libelle', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin_demandee', models.DateField()),
                ('date_fin_validee', models.DateField(blank=True, help_text='Peut différer de date_fin_demandee si le directeur valide pour une durée différente.', null=True)),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_COURS', 'En cours de validation'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('ANNULEE', "Annulée par l'agent")], default='BROUILLON', max_length=20)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('soumise_le', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_conge', to=settings.AUTH_USER_MODEL)),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='conges.typeconge')),
            ],
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('hash_verification', models.CharField(editable=False, max_length=64)),
                ('fichier_pdf', models.FileField(upload_to='attestations/%Y/%m/')),
                ('generee_le', models.DateTimeField(auto_now_add=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='attestation', to='conges.demandeconge')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCongeJustificatifRequis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs_requis', to='conges.typeconge')),
                ('type_justificatif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conges.typejustificatif')),
            ],
        ),
        migrations.CreateModel(
            name='JustificatifDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to=conges.models.chemin_justificatif)),
                ('depose_le', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificatifs', to='conges.demandeconge')),
                ('type_justificatif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conges.typejustificatif')),
            ],
        ),
        migrations.CreateModel(
            name='EtapeValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField()),
                ('role_attendu', models.CharField(help_text='Rôle du validateur au moment de la génération.', max_length=20)),
                ('decision', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée')], default='EN_ATTENTE', max_length=20)),
                ('duree_accordee_jours', models.PositiveIntegerField(blank=True, help_text='Renseigné par le directeur si la durée validée diffère de la demande.', null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('decide_le', models.DateTimeField(blank=True, null=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='conges.demandeconge')),
                ('validateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapes_a_valider', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['demande', 'ordre'],
                'unique_together': {('demande', 'ordre')},
            },
        ),
        migrations.AddIndex(
            model_name='demandeconge',
            index=models.Index(fields=['agent', 'statut'], name='conges_dema_agent_i_a4e17f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='typecongejustificatifrequis',
            unique_together={('type_conge', 'type_justificatif')},
        ),
    ]
